### ISSUE TITLE
plugin-uploader: failes to upload plugin

### ISSUE THREAD

**Issue by zaki-yama** [kintone/js-sdk#886]
## Target Package

- `@kintone/plugin-uploader@4.3.1` or later

## Environment

- Operating System: any
- Browser: N.A.
- Node.js version: any (>= 12)

## Current Behavior

Currently 

```
$ npm install -g @kintone/plugin-uploader
$ kintone-plugin-uploader <path-to-plugin-file>
Open https://xxx.cybozu.com/login?saml=off
Trying to log in...
Navigate to https://xxx.cybozu.com/k/admin/system/plugin/
Trying to upload SAMPLE_text_connet_plugin_v1.3.4.zip
エラーが発生しました TimeoutError: waiting for selector `.ocean-ui-dialog` to be hidden failed: timeout 60000ms exceeded
    at new WaitTask (/Users/***/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:509:34)
    at DOMWorld.waitForSelectorInPage (/Users/***/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:420:26)
    at Object.internalHandler.waitFor (/Users/***/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (/Users/***/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:313:29)
    at Frame.waitForSelector (/Users/***/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:841:51)
    at Page.waitForSelector (/Users/***/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1333:33)
    at /Users/***/node_modules/@kintone/plugin-uploader/dist/index.js:83:20
    at Generator.next (<anonymous>)
    at fulfilled (/Users/***/node_modules/@kintone/plugin-uploader/dist/index.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
✨  Done in 65.09s.
```

## Expected Behavior

Can successfully upload the plugin.

## Workaround

Use `@kintone/plugin-uploader@4.3.0`.

**Comment by zaki-yama** [comment]
We pinned the puppeteer version to v8 in #889 as a temporary fix.
